/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuyModel } from './buyModel';
import { Buy } from './buy';


export interface BuyCreate { 
    buy: Buy;
    /**
     * Thông tin về các phân loại hàng được mua trong đơn nhập. Được lưu tại bảng buy_model. Dữ liệu này được sử dụng để làm bảng kho
     */
    buyModel: Array<BuyModel>;
}

