/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItem } from './orderItem';


export interface BuyerUser { 
    phone_public?: boolean;
    buyer_rating?: number;
    user_id: number;
    language?: string;
    hide_likes?: number;
    rating_star?: number;
    cb_option?: number;
    followed?: boolean;
    ext_info?: OrderItem;
    phone?: string;
    rating_count?: Array<number>;
    delivery_order_count?: number;
    shop_id: number;
    portrait?: string;
    delivery_succ_count?: number;
    password?: string;
    user_name?: string;
    email?: string;
}

