/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuyModel { 
    /**
     * Id của document do mình quản lý
     */
    gomdon_id?: string;
    /**
     * Id của đơn mua (Được liên kết đến trường gomdon_id của bảng Buy)
     */
    gomdon_buy_id?: string;
    gomdon_status?: BuyModel.GomdonStatusEnum;
    /**
     * Số lượng thực tế nhận được
     */
    actual_quantity?: number;
    /**
     * Id của sản phẩm trên trang 1688 (Có thể lấy từ bảng sản phẩm)
     */
    linked_product_id: string;
    /**
     * Lấy từ bảng sản phẩm
     */
    image?: string;
    /**
     * Tên tiếng việt của phân loại
     */
    gomdon_name?: string;
    /**
     * link đến gomdon_sku của ProductClassify
     */
    gomdon_sku: string;
    /**
     * giá nhập
     */
    price: number;
    /**
     * Số lượng của phân loại (lấy trên đơn mua của 1688)
     */
    quantity: number;
    height?: number;
    length?: number;
    /**
     * link đến gomdon_id của bảng products
     */
    gomdon_product_id: string;
    /**
     * Tên tiếng việt của sản phẩm
     */
    gomdon_product_name?: string;
    width?: number;
    weight?: number;
    /**
     * Tên phân loại trên 1688
     */
    sku_name?: string;
    /**
     * sku phân loại trên 1688
     */
    skuId: string;
    /**
     * Số lượng hàng có trong kho
     */
    stock?: number;
}
export namespace BuyModel {
    export type GomdonStatusEnum = 1 | 2 | 3;
    export const GomdonStatusEnum = {
        NUMBER_1: 1 as GomdonStatusEnum,
        NUMBER_2: 2 as GomdonStatusEnum,
        NUMBER_3: 3 as GomdonStatusEnum
    };
}


