/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuyModelUpdate { 
    /**
     * id san pham
     */
    gomdon_product_id: string;
    gomdon_sku: string;
    /**
     * ten phan loai
     */
    gomdon_name?: string;
    /**
     * id don nhap
     */
    gomdon_buy_id?: string;
    /**
     * thuc nhap
     */
    actual_quantity?: number;
}

