/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BuyUpdateBuyModelIds } from './buyUpdateBuyModelIds';
import { BuyUpdateData } from './buyUpdateData';


export interface BuyUpdate { 
    buy_model_ids?: Array<BuyUpdateBuyModelIds>;
    /**
     * id document của bảng buys
     */
    gomdon_id: string;
    data: BuyUpdateData;
}

