/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BuyUpdateBuyModelIds { 
    /**
     * id phan loai hang
     */
    gomdon_id?: string;
    /**
     * so luong thuc nhap cua phan loai
     */
    actual_quantity?: number;
}

