/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ExportUpdateData { 
    gomdon_status?: ExportUpdateData.GomdonStatusEnum;
}
export namespace ExportUpdateData {
    export type GomdonStatusEnum = 1 | 2 | 3 | 4;
    export const GomdonStatusEnum = {
        NUMBER_1: 1 as GomdonStatusEnum,
        NUMBER_2: 2 as GomdonStatusEnum,
        NUMBER_3: 3 as GomdonStatusEnum,
        NUMBER_4: 4 as GomdonStatusEnum
    };
}


