/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject2 { 
    uid: string;
    role: InlineObject2.RoleEnum;
}
export namespace InlineObject2 {
    export type RoleEnum = 'quanlykho' | 'CTVban' | 'nguoimoi';
    export const RoleEnum = {
        Quanlykho: 'quanlykho' as RoleEnum,
        CTVban: 'CTVban' as RoleEnum,
        Nguoimoi: 'nguoimoi' as RoleEnum
    };
}


