/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface InlineObject7 { 
    action: InlineObject7.ActionEnum;
    gomdon_id: string;
}
export namespace InlineObject7 {
    export type ActionEnum = 'duyet' | 'huy';
    export const ActionEnum = {
        Duyet: 'duyet' as ActionEnum,
        Huy: 'huy' as ActionEnum
    };
}


