/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ItemModel { 
    status?: number;
    model_id: number;
    name: string;
    price: string;
    ctime?: number;
    currency?: string;
    /**
     * sku được lấy ở phân loại sản phẩn trang shopee. sku này được link đến gomdon_sku của sản phẩm. Dựa vào sku này để trừ tồn kho trong bảng BuyModel
     */
    sku: string;
    mtime?: number;
    item_id: number;
    promotion_id?: number;
    price_before_discount?: string;
    rebate_price?: string;
    sold?: number;
    stock?: number;
}

