/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductSell } from './productSell';
import { ItemModel } from './itemModel';


export interface OrderItem { 
    /**
     * link đến gomdon_id của bảng Sell
     */
    gomdon_sell_id?: string;
    status?: number;
    is_add_on_sub_item?: boolean;
    product: ProductSell;
    item_price: string;
    bundle_deal_product?: Array<string>;
    bundle_deal_id?: number;
    is_wholesale?: boolean;
    comm_fee_rate?: string;
    bundle_deal?: number;
    amount: number;
    shop_id?: number;
    bundle_deal_model?: Array<string>;
    order_price: string;
    snapshot_id?: number;
    item_id: number;
    item_model: ItemModel;
    add_on_deal_id?: number;
    group_id?: number;
    item_list?: Array<string>;
    model_id: number;
    price_before_bundle?: string;
}

