/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductClassify { 
    /**
     * Tên tiếng việt của phân loại
     */
    gomdon_name: string;
    /**
     * sku này do mình quản lý
     */
    gomdon_sku?: string;
    /**
     * tên trung quốc của phân loại lấy trên 1688
     */
    sku_name?: string;
    /**
     * skuid của phân loại trên 1688
     */
    skuId?: string;
    image: string;
    length?: number;
    width?: number;
    height?: number;
    weight?: number;
    specId?: string;
    saleCount?: number;
    discountPrice?: number;
    canBookCount?: number;
}

