/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductClassify } from './productClassify';


export interface ProductUpdateData { 
    classify?: Array<ProductClassify>;
    gomdon_product_name?: string;
    image_preview?: string;
}

