/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductUpdateData } from './productUpdateData';


/**
 * Model này dùng để validate product khi gửi lên để update
 */
export interface ProductUpdate { 
    gomdon_id: string;
    data: ProductUpdateData;
}

