/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Responses { 
    code: Responses.CodeEnum;
    data: Array<object> | object | string;
}
export namespace Responses {
    export type CodeEnum = 'success' | 'error';
    export const CodeEnum = {
        Success: 'success' as CodeEnum,
        Error: 'error' as CodeEnum
    };
}


