/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellPaidCheck { 
    /**
     * thời gian shopee chuyển tiền
     */
    date?: string;
    /**
     * Tiền shopee chuyển vào ví
     */
    paid: number;
    /**
     * Tiền vận chuyển đến ví shopee hay thẻ ngân hàng
     */
    move_in?: string;
    /**
     * Trường order_sn trong bảng sell
     */
    id: string;
    /**
     * số dư của ví shopee
     */
    balance?: number;
    desc?: string;
}

