/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SellerAddressEXTInfo } from './sellerAddressEXTInfo';


export interface SellerAddress { 
    status?: number;
    city?: string;
    address_id?: number;
    user_id?: number;
    name?: string;
    district?: string;
    country?: string;
    town?: string;
    mtime?: number;
    logistics_status?: number;
    full_address?: string;
    ext_info?: SellerAddressEXTInfo;
    phone?: string;
    state?: string;
    def_time?: number;
    address?: string;
    icno?: string;
    zip_code?: string;
    ctime?: number;
}

