/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SellCreateReceiptTransactionLogs { 
    /**
     * mã phiếu thu tiền
     */
    receiptId?: string;
    uid?: string;
    name?: string;
    /**
     * số tiền nhận được
     */
    money_receive?: number;
    date_receive?: string;
}

