/**
 * Gom Don API
 * Gom Don API.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: huynhnhon.dev@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TransactionLog { 
    desc?: string;
    move_in?: number;
    name?: string;
    gomdon_ctime?: number;
    money_receive?: number;
    balance?: number;
    uid?: string;
    receiptId?: string;
}

